AWSTemplateFormatVersion: '2010-09-09'
Description: "This template creates an SFTP server in the specific region for transferring files."

# parameter to specify the email address for DataOps notifications with valid email format
Parameters:
  DataOpsEmail:
    Type: String
    Description: The email address for DataOps notifications
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

Resources:
  SFTPServer:
    Type: 'AWS::Transfer::Server'
    Properties:
      EndpointType: 'PUBLIC'
      Protocols:
        - 'SFTP'
      IdentityProviderType: 'SERVICE_MANAGED'

  NotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'sftp-server-logging-topic'
      Subscription:
        - Protocol: email
          Endpoint: !Ref DataOpsEmail

Outputs:
  DataOpsEmail:
    Description: 'The email address for DataOps notifications.'
    Value: !Ref DataOpsEmail
    Export:
      Name: 'data-ops-email'
  SFTPServerEndpoint:
    Description: 'The endpoint of the SFTP server.'
    Value: !Sub '${SFTPServer.ServerId}.server.transfer.${AWS::Region}.amazonaws.com'
    Export:
      Name: 'sftp-server-endpoint'
  SFTPServerId:
    Description: 'The ID of the SFTP server.'
    Value: !GetAtt SFTPServer.ServerId
    Export:
      Name: 'sftp-server-id'
  SNSTopicArn:
    Description: 'The ARN of the SNS topic for DataOps notifications.'
    Value: !Ref NotificationTopic
    Export:
      Name: 'data-ops-sns-topic-arn'