AWSTemplateFormatVersion: '2010-09-09'
Description: "This template creates an SFTP server in the specific region for transferring files."

Resources:

  SFTPServer:
    Type: 'AWS::Transfer::Server'
    Properties:
      EndpointType: 'PUBLIC'
      Protocols:
        - 'SFTP'
      IdentityProviderType: 'SERVICE_MANAGED'
      LoggingRole: !GetAtt LoggingRole.Arn

  NotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      KmsMasterKeyId: 'alias/aws/sns'
      TopicName: 'sftp-server-logging-topic'
 
  LoggingRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'transfer.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      RoleName: 'TransferLoggingRole'
      Policies:
        - PolicyName: 'TransferLoggingPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
Outputs:
  SFTPServerEndpoint:
    Description: 'The endpoint of the SFTP server.'
    Value: !Sub '${SFTPServer.ServerId}.server.transfer.${AWS::Region}.amazonaws.com'
    Export:
      Name: 'sftp-server-endpoint'
  SFTPServerId:
    Description: 'The ID of the SFTP server.'
    Value: !GetAtt SFTPServer.ServerId
    Export:
      Name: 'sftp-server-id'
  SNSTopicArn:
    Description: 'The ARN of the SNS topic for DataOps notifications.'
    Value: !Ref NotificationTopic
    Export:
      Name: 'data-ops-sns-topic-arn'