AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Owner:
    Type: String
    Description: "The owner of the resources used for tagging"
    Default: "warrenne@gmail.com"
  
  GitHubOwner:
    Type: String
    Description: "The owner of the GitHub repository used for syncing"
    Default: "Warrenn"

  Product:
    Type: String
    Description: "The product name used for tagging"
    Default: "tha-warrenn-enslin"

  RepositoryName:
    Type: String
    Description: "The name of the repository"
    Default: "THA_Warrenn-Enslin"

  Branch:
    Type: String
    Description: "The name of the branch"
    Default: "main"

  ConfigFile:
    Type: String
    Description: "The path of the config file"
    Default: "cloudformation/sftp-server/sftp-server-config.yaml"
  
  StackName:
    Type: String
    Description: "The name of the stack"
    Default: "sftp-server"

Resources:
  # Define the CodeStar Connection
  GitHubConnection:
    Type: 'AWS::CodeStarConnections::Connection'
    Properties:
      ConnectionName: 'GitHubConnection'  # Name for the GitHub connection
      ProviderType: 'GitHub'  # GitHub as the provider
      Tags:
        - Key: owner
          Value: !Ref Owner
        - Key: product
          Value: !Ref Product

  RepositoryLink:
    Type: AWS::CodeStarConnections::RepositoryLink
    Properties:
      ConnectionArn: !GetAtt GitHubConnection.ConnectionArn
      OwnerId: !Ref GitHubOwner
      RepositoryName: !Ref RepositoryName
      Tags:
        - Key: owner
          Value: !Ref Owner
        - Key: product
          Value: !Ref Product

  SyncConfiguration:
    Type: AWS::CodeStarConnections::SyncConfiguration
    Properties:
      Branch: !Ref Branch
      ConfigFile: !Ref ConfigFile
      PublishDeploymentStatus: "ENABLED"
      RepositoryLinkId: !GetAtt RepositoryLink.RepositoryLinkId
      ResourceName: !Ref StackName
      RoleArn: !GetAtt SyncRole.Arn
      SyncType: "CFN_STACK_SYNC"
  
  SyncRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.sync.codeconnections.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CodeStarConnections
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Sid: "SyncToCloudFormation"
              Effect: "Allow"
              Action:
                - "cloudformation:CreateChangeSet"
                - "cloudformation:DeleteChangeSet"
                - "cloudformation:DescribeChangeSet"
                - "cloudformation:DescribeStackEvents"
                - "cloudformation:DescribeStacks"
                - "cloudformation:ExecuteChangeSet"
                - "cloudformation:GetTemplate"
                - "cloudformation:ListChangeSets"
                - "cloudformation:ListStacks"
                - "cloudformation:ValidateTemplate"
              Resource: "*"

            - Sid: "PolicyForManagedRules"
              Effect: "Allow"
              Action:
                - "events:PutRule"
                - "events:PutTargets"
              Resource: "*"
              Condition:
                StringEquals:
                  events:ManagedBy:
                    - "cloudformation.sync.codeconnections.amazonaws.com"

            - Sid: "PolicyForDescribingRule"
              Effect: "Allow"
              Action: "events:DescribeRule"
              Resource: "*"
      Tags:
        - Key: owner
          Value: !Ref Owner
        - Key: product
          Value: !Ref Product
Outputs:
  GitHubConnectionArn:
    Description: 'The ARN of the GitHub connection.'
    Value: !GetAtt GitHubConnection.ConnectionArn
